kind: Service
apiVersion: v1
metadata:
  name: todo-app-service-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: todo-app-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
